// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_89QJlVdazTl2nK0iNQe-a9PODP6Qyw',
    appId: '1:933969173371:web:4f6058fad209c61416fbde',
    messagingSenderId: '933969173371',
    projectId: 'chat-app-1dbfa',
    authDomain: 'chat-app-1dbfa.firebaseapp.com',
    storageBucket: 'chat-app-1dbfa.appspot.com',
    measurementId: 'G-V4FXKTWPRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG58xg_MmSv3NH4InqEz196RKhXKNM2Ps',
    appId: '1:933969173371:android:8d0ccf1b4b49846d16fbde',
    messagingSenderId: '933969173371',
    projectId: 'chat-app-1dbfa',
    storageBucket: 'chat-app-1dbfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0A-dhotdLLmfbP6gjHCldZ78st_cclI',
    appId: '1:933969173371:ios:c47c9e7551c499dc16fbde',
    messagingSenderId: '933969173371',
    projectId: 'chat-app-1dbfa',
    storageBucket: 'chat-app-1dbfa.appspot.com',
    iosBundleId: 'com.luna.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0A-dhotdLLmfbP6gjHCldZ78st_cclI',
    appId: '1:933969173371:ios:c47c9e7551c499dc16fbde',
    messagingSenderId: '933969173371',
    projectId: 'chat-app-1dbfa',
    storageBucket: 'chat-app-1dbfa.appspot.com',
    iosBundleId: 'com.luna.chattingApp',
  );
}
